#!/bin/bash
# Run rebuild/benchmark under one exclusive lock and keep benchmark logs clean.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
[ -f "$SCRIPT_DIR/env.sh" ] && source "$SCRIPT_DIR/env.sh"

LOCK_FILE="${ISUCON_LOCK_FILE:-/tmp/isucon-bench.lock}"
RESET_LOGS_BEFORE="${RESET_LOGS_BEFORE:-1}"
RUN_REBUILD="${RUN_REBUILD:-0}"
SLEEP_AFTER_REBUILD="${SLEEP_AFTER_REBUILD:-2}"
WAIT_SERVICES_TIMEOUT="${WAIT_SERVICES_TIMEOUT:-30}"

usage() {
  cat <<'EOF'
Usage:
  scripts/bench-locked.sh [--rebuild] [--no-reset-logs]

Environment:
  BENCH_CMD            benchmark command from scripts/env.sh
  REBUILD_CMD          rebuild/restart command from scripts/env.sh
  NGINX_ACCESS_LOG     access log truncated before benchmark by default
  MYSQL_SLOW_LOG       slow log truncated before benchmark by default
  HEALTHCHECK_CMD      optional command checked before benchmark
  ISUCON_LOCK_FILE     lock path, default: /tmp/isucon-bench.lock
  RESET_LOGS_BEFORE    1 to truncate logs before benchmark, default: 1
  WAIT_SERVICES_TIMEOUT seconds to wait for services, default: 30
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --rebuild)
      RUN_REBUILD=1
      ;;
    --no-reset-logs)
      RESET_LOGS_BEFORE=0
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[bench-locked] unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

if [ -z "${BENCH_CMD:-}" ]; then
  echo "[bench-locked] BENCH_CMD is empty. Run /isucon-survey first." >&2
  exit 1
fi
if [ "$RUN_REBUILD" = "1" ] && [ -z "${REBUILD_CMD:-}" ]; then
  echo "[bench-locked] REBUILD_CMD is empty." >&2
  exit 1
fi

truncate_log() {
  local path="$1"
  [ -n "$path" ] || return 0
  [ -f "$path" ] || return 0
  truncate -s 0 "$path"
}

wait_for_services() {
  if [ -n "${HEALTHCHECK_CMD:-}" ]; then
    echo "[bench-locked] waiting for HEALTHCHECK_CMD..."
    local deadline=$((SECONDS + WAIT_SERVICES_TIMEOUT))
    until eval "$HEALTHCHECK_CMD"; do
      if [ "$SECONDS" -ge "$deadline" ]; then
        echo "[bench-locked] HEALTHCHECK_CMD did not pass within ${WAIT_SERVICES_TIMEOUT}s" >&2
        return 1
      fi
      sleep 1
    done
  fi

  if [ "${ISUCON_RUNTIME:-}" = "docker" ] && [ -n "${DOCKER_COMPOSE_DIR:-}" ]; then
    local compose_file="$DOCKER_COMPOSE_DIR/compose.yml"
    [ -f "$compose_file" ] || compose_file="$DOCKER_COMPOSE_DIR/docker-compose.yml"
    [ -f "$compose_file" ] || return 0

    compose_for_env() {
      if [ -n "${DOCKER_COMPOSE_FILE_ARGS:-}" ]; then
        # DOCKER_COMPOSE_FILE_ARGS is generated by /isucon-survey and contains
        # the base compose file plus optional analysis overrides.
        eval "docker compose $DOCKER_COMPOSE_FILE_ARGS \"\$@\""
      else
        docker compose -f "$compose_file" "$@"
      fi
    }

    echo "[bench-locked] waiting for docker compose services..."
    local expected running deadline
    expected="$(compose_for_env config --services | sort)"
    deadline=$((SECONDS + WAIT_SERVICES_TIMEOUT))
    while :; do
      running="$(compose_for_env ps --services --status running | sort)"
      if [ "$expected" = "$running" ]; then
        return 0
      fi
      if [ "$SECONDS" -ge "$deadline" ]; then
        echo "[bench-locked] services are not all running within ${WAIT_SERVICES_TIMEOUT}s" >&2
        compose_for_env ps >&2 || true
        return 1
      fi
      sleep 1
    done
  fi
}

flock "$LOCK_FILE" bash -lc '
  set -euo pipefail
  [ -f "'"$SCRIPT_DIR"'/env.sh" ] && source "'"$SCRIPT_DIR"'/env.sh"
'"$(declare -f wait_for_services)"'

  if [ "'"$RESET_LOGS_BEFORE"'" = "1" ]; then
    [ -n "${NGINX_ACCESS_LOG:-}" ] && [ -f "$NGINX_ACCESS_LOG" ] && truncate -s 0 "$NGINX_ACCESS_LOG"
    [ -n "${MYSQL_SLOW_LOG:-}" ] && [ -f "$MYSQL_SLOW_LOG" ] && truncate -s 0 "$MYSQL_SLOW_LOG"
  fi

  if [ "'"$RUN_REBUILD"'" = "1" ]; then
    eval "$REBUILD_CMD"
    sleep "'"$SLEEP_AFTER_REBUILD"'"
  fi

  WAIT_SERVICES_TIMEOUT="'"$WAIT_SERVICES_TIMEOUT"'"
  wait_for_services

  eval "$BENCH_CMD"
'

echo "[bench-locked] benchmark finished. Run scripts/analyze.sh before the next benchmark to analyze this clean log window."
