#!/bin/bash
# Run rebuild/benchmark under one exclusive lock and keep benchmark logs clean.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
[ -f "$SCRIPT_DIR/env.sh" ] && source "$SCRIPT_DIR/env.sh"

LOCK_FILE="${ISUCON_LOCK_FILE:-/tmp/isucon-bench.lock}"
RESET_LOGS_BEFORE="${RESET_LOGS_BEFORE:-1}"
RUN_REBUILD="${RUN_REBUILD:-0}"
SLEEP_AFTER_REBUILD="${SLEEP_AFTER_REBUILD:-2}"
WAIT_SERVICES_TIMEOUT="${WAIT_SERVICES_TIMEOUT:-30}"

# 常時メトリクス取得（dstat / docker stats / Go GC トレース）
RUNTIME_DIR="${ISUCON_RUNTIME_DIR:-$REPO_DIR/reports/.runtime}"
DSTAT_LOG="$RUNTIME_DIR/dstat.csv"
DOCKER_STATS_LOG="$RUNTIME_DIR/docker-stats.log"
GC_TRACE_LOG="$RUNTIME_DIR/gc-trace.log"
DSTAT_INTERVAL="${DSTAT_INTERVAL:-1}"
DOCKER_STATS_INTERVAL="${DOCKER_STATS_INTERVAL:-2}"
ENABLE_DSTAT="${ENABLE_DSTAT:-1}"
ENABLE_DOCKER_STATS="${ENABLE_DOCKER_STATS:-1}"
ENABLE_GC_TRACE="${ENABLE_GC_TRACE:-1}"

usage() {
  cat <<'EOF'
Usage:
  scripts/bench-locked.sh [--rebuild] [--no-reset-logs]

Environment:
  BENCH_CMD             benchmark command from scripts/env.sh
  REBUILD_CMD           rebuild/restart command from scripts/env.sh
  NGINX_ACCESS_LOG      access log truncated before benchmark by default
  MYSQL_SLOW_LOG        slow log truncated before benchmark by default
  HEALTHCHECK_CMD       optional command checked before benchmark
  ISUCON_LOCK_FILE      lock path, default: /tmp/isucon-bench.lock
  RESET_LOGS_BEFORE     1 to truncate logs before benchmark, default: 1
  WAIT_SERVICES_TIMEOUT seconds to wait for services, default: 30
  APP_SERVICES          app service names (space separated): docker compose service names or systemd unit names, used for GC trace capture
  ENABLE_DSTAT          1 to record dstat during benchmark, default: 1 (skipped if dstat not installed)
  ENABLE_DOCKER_STATS   1 to record docker stats during benchmark, default: 1 (skipped if ISUCON_RUNTIME != docker)
  ENABLE_GC_TRACE       1 to capture Go GC trace during benchmark, default: 1 (skipped unless ISUCON_APP_LANG=go and APP_SERVICES set)
  DSTAT_INTERVAL        dstat sampling interval in seconds, default: 1
  DOCKER_STATS_INTERVAL docker stats sampling interval in seconds, default: 2

Raw output consumed by scripts/analyze.sh:
  reports/.runtime/dstat.csv
  reports/.runtime/docker-stats.log
  reports/.runtime/gc-trace.log
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --rebuild)
      RUN_REBUILD=1
      ;;
    --no-reset-logs)
      RESET_LOGS_BEFORE=0
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[bench-locked] unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

if [ -z "${BENCH_CMD:-}" ]; then
  echo "[bench-locked] BENCH_CMD is empty. Run /isucon-survey first." >&2
  exit 1
fi
if [ "$RUN_REBUILD" = "1" ] && [ -z "${REBUILD_CMD:-}" ]; then
  echo "[bench-locked] REBUILD_CMD is empty." >&2
  exit 1
fi

truncate_log() {
  local path="$1"
  [ -n "$path" ] || return 0
  [ -f "$path" ] || return 0
  truncate -s 0 "$path"
}

compose_for_env() {
  if [ -n "${DOCKER_COMPOSE_FILE_ARGS:-}" ]; then
    # DOCKER_COMPOSE_FILE_ARGS is generated by /isucon-survey and contains
    # the base compose file plus optional analysis overrides.
    eval "docker compose $DOCKER_COMPOSE_FILE_ARGS \"\$@\""
  else
    local compose_file="${DOCKER_COMPOSE_DIR:-.}/compose.yml"
    [ -f "$compose_file" ] || compose_file="${DOCKER_COMPOSE_DIR:-.}/docker-compose.yml"
    docker compose -f "$compose_file" "$@"
  fi
}

wait_for_services() {
  if [ -n "${HEALTHCHECK_CMD:-}" ]; then
    echo "[bench-locked] waiting for HEALTHCHECK_CMD..."
    local deadline=$((SECONDS + WAIT_SERVICES_TIMEOUT))
    until eval "$HEALTHCHECK_CMD"; do
      if [ "$SECONDS" -ge "$deadline" ]; then
        echo "[bench-locked] HEALTHCHECK_CMD did not pass within ${WAIT_SERVICES_TIMEOUT}s" >&2
        return 1
      fi
      sleep 1
    done
  fi

  if [ "${ISUCON_RUNTIME:-}" = "docker" ] && [ -n "${DOCKER_COMPOSE_DIR:-}" ]; then
    local compose_file="$DOCKER_COMPOSE_DIR/compose.yml"
    [ -f "$compose_file" ] || compose_file="$DOCKER_COMPOSE_DIR/docker-compose.yml"
    [ -f "$compose_file" ] || return 0

    echo "[bench-locked] waiting for docker compose services..."
    local expected running deadline
    expected="$(compose_for_env config --services | sort)"
    deadline=$((SECONDS + WAIT_SERVICES_TIMEOUT))
    while :; do
      running="$(compose_for_env ps --services --status running | sort)"
      if [ "$expected" = "$running" ]; then
        return 0
      fi
      if [ "$SECONDS" -ge "$deadline" ]; then
        echo "[bench-locked] services are not all running within ${WAIT_SERVICES_TIMEOUT}s" >&2
        compose_for_env ps >&2 || true
        return 1
      fi
      sleep 1
    done
  fi
}

start_dstat() {
  [ "$ENABLE_DSTAT" = "1" ] || return 0
  if ! command -v dstat &>/dev/null; then
    echo "[bench-locked] dstat not installed, skipping. Run scripts/setup-tools.sh." >&2
    return 0
  fi
  mkdir -p "$RUNTIME_DIR"
  dstat -tcmdn --output "$DSTAT_LOG" "$DSTAT_INTERVAL" > /dev/null 2>&1 &
  echo $! > "$RUNTIME_DIR/dstat.pid"
}

stop_dstat() {
  [ -f "$RUNTIME_DIR/dstat.pid" ] || return 0
  kill "$(cat "$RUNTIME_DIR/dstat.pid")" 2>/dev/null || true
  rm -f "$RUNTIME_DIR/dstat.pid"
}

start_docker_stats() {
  [ "$ENABLE_DOCKER_STATS" = "1" ] || return 0
  [ "${ISUCON_RUNTIME:-}" = "docker" ] || return 0
  mkdir -p "$RUNTIME_DIR"
  : > "$DOCKER_STATS_LOG"
  (
    while :; do
      { echo "=== $(date '+%Y-%m-%d %H:%M:%S') ==="; docker stats --no-stream; } >> "$DOCKER_STATS_LOG" 2>&1
      sleep "$DOCKER_STATS_INTERVAL"
    done
  ) &
  echo $! > "$RUNTIME_DIR/docker-stats.pid"
}

stop_docker_stats() {
  [ -f "$RUNTIME_DIR/docker-stats.pid" ] || return 0
  kill "$(cat "$RUNTIME_DIR/docker-stats.pid")" 2>/dev/null || true
  rm -f "$RUNTIME_DIR/docker-stats.pid"
}

capture_gc_trace() {
  [ "$ENABLE_GC_TRACE" = "1" ] || return 0
  [ "${ISUCON_APP_LANG:-}" = "go" ] || return 0
  [ -n "${APP_SERVICES:-}" ] || return 0
  [ -n "${1:-}" ] || return 0
  mkdir -p "$RUNTIME_DIR"
  local epoch="$1"
  if [ "${ISUCON_RUNTIME:-}" = "docker" ]; then
    local since_rfc3339
    since_rfc3339="$(date -d "@$epoch" "+%Y-%m-%dT%H:%M:%S%:z")"
    compose_for_env logs --no-color --since "$since_rfc3339" $APP_SERVICES > "$GC_TRACE_LOG" 2>&1 || true
  elif [ "${ISUCON_RUNTIME:-}" = "systemd" ]; then
    local since_journal svc
    since_journal="$(date -d "@$epoch" "+%Y-%m-%d %H:%M:%S")"
    : > "$GC_TRACE_LOG"
    for svc in $APP_SERVICES; do
      sudo journalctl -u "$svc" --since "$since_journal" --no-pager >> "$GC_TRACE_LOG" 2>&1 || true
    done
  fi
}

flock "$LOCK_FILE" bash -lc '
  set -euo pipefail
  [ -f "'"$SCRIPT_DIR"'/env.sh" ] && source "'"$SCRIPT_DIR"'/env.sh"
'"$(declare -f compose_for_env)"'
'"$(declare -f wait_for_services)"'
'"$(declare -f start_dstat)"'
'"$(declare -f stop_dstat)"'
'"$(declare -f start_docker_stats)"'
'"$(declare -f stop_docker_stats)"'
'"$(declare -f capture_gc_trace)"'

  RUNTIME_DIR="'"$RUNTIME_DIR"'"
  DSTAT_LOG="'"$DSTAT_LOG"'"
  DOCKER_STATS_LOG="'"$DOCKER_STATS_LOG"'"
  GC_TRACE_LOG="'"$GC_TRACE_LOG"'"
  DSTAT_INTERVAL="'"$DSTAT_INTERVAL"'"
  DOCKER_STATS_INTERVAL="'"$DOCKER_STATS_INTERVAL"'"
  ENABLE_DSTAT="'"$ENABLE_DSTAT"'"
  ENABLE_DOCKER_STATS="'"$ENABLE_DOCKER_STATS"'"
  ENABLE_GC_TRACE="'"$ENABLE_GC_TRACE"'"

  if [ "'"$RESET_LOGS_BEFORE"'" = "1" ]; then
    [ -n "${NGINX_ACCESS_LOG:-}" ] && [ -f "$NGINX_ACCESS_LOG" ] && truncate -s 0 "$NGINX_ACCESS_LOG"
    [ -n "${MYSQL_SLOW_LOG:-}" ] && [ -f "$MYSQL_SLOW_LOG" ] && truncate -s 0 "$MYSQL_SLOW_LOG"
  fi

  if [ "'"$RUN_REBUILD"'" = "1" ]; then
    eval "$REBUILD_CMD"
    sleep "'"$SLEEP_AFTER_REBUILD"'"
  fi

  WAIT_SERVICES_TIMEOUT="'"$WAIT_SERVICES_TIMEOUT"'"
  wait_for_services

  BENCH_START="$(date +%s)"
  start_dstat
  start_docker_stats

  set +e
  eval "$BENCH_CMD"
  BENCH_STATUS=$?

  stop_dstat
  stop_docker_stats
  capture_gc_trace "$BENCH_START"

  exit "$BENCH_STATUS"
'

echo "[bench-locked] benchmark finished. Run scripts/analyze.sh before the next benchmark to analyze this clean log window."
