#!/bin/bash
# ISUCON nginx LTSV アクセスログ設定
# nginx が動いているサーバーで実行する。nginx がなければ何もしない。
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"

log() { echo "[setup-nginx] $*"; }

if [ ! -f "/etc/nginx/nginx.conf" ]; then
  log "nginx not found, skipping"
  exit 0
fi

if grep -rE '^\s*log_format\s+ltsv' /etc/nginx/ &>/dev/null; then
  log "nginx LTSV already configured"
  if grep -rE '^\s*access_log\s+[^;]+;' /etc/nginx/ 2>/dev/null | grep -vq 'ltsv'; then
    log "ERROR: some access_log directives do not use ltsv."
    log "  Run 'sudo nginx -T' and update server/location access_log directives before analyzing logs."
    exit 1
  fi
  exit 0
fi

log "Setting up nginx LTSV access log..."
sudo mkdir -p /etc/nginx/conf.d
if [ -f /etc/nginx/conf.d/ltsv.conf ] && ! sudo grep -q 'Generated by setup-nginx.sh' /etc/nginx/conf.d/ltsv.conf; then
  log "ERROR: /etc/nginx/conf.d/ltsv.conf exists and was not generated by setup-nginx.sh."
  log "  Move it aside or merge templates/nginx-ltsv.conf manually."
  exit 1
fi
sudo cp "$REPO_DIR/templates/nginx-ltsv.conf" /etc/nginx/conf.d/ltsv.conf
sudo nginx -t && sudo systemctl reload nginx
if grep -rE '^\s*access_log\s+[^;]+;' /etc/nginx/ 2>/dev/null | grep -vq 'ltsv'; then
  log "ERROR: existing server/location access_log may override the http-level ltsv log."
  log "  Run 'sudo nginx -T' and update those access_log directives to use ltsv."
  exit 1
fi
log "nginx LTSV log enabled"
