#!/bin/bash
# Docker Compose 環境向け ISUCON セットアップ
# - ログをホストに volume マウント（docker-compose.isucon-logs.yml）
# - nginx LTSV ログ設定を適用
# - MySQL スロークエリログを有効化
# 事前に /isucon-survey で scripts/env.sh を生成しておくこと。
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"

# /isucon-survey が生成した env.sh を読む（存在すれば）
[ -f "$SCRIPT_DIR/env.sh" ] && source "$SCRIPT_DIR/env.sh"

log() { echo "[setup-docker] $*"; }

# ---- compose ファイル・サービスを特定 ----
find_compose_dir() {
  if [ -n "${DOCKER_COMPOSE_DIR:-}" ]; then
    realpath "$DOCKER_COMPOSE_DIR"; return
  fi
  for dir in "." "${ISUCON_WEBAPP_DIR:-/home/isucon/webapp}"; do
    [ -z "$dir" ] && continue
    if [ -f "$dir/compose.yml" ] || [ -f "$dir/docker-compose.yml" ]; then
      realpath "$dir"; return
    fi
  done
  echo ""
}

COMPOSE_DIR="$(find_compose_dir)"
if [ -z "$COMPOSE_DIR" ]; then
  log "ERROR: compose.yml not found."
  log "  Run /isucon-survey to generate scripts/env.sh, or set DOCKER_COMPOSE_DIR=<path>."
  exit 1
fi
COMPOSE_FILE="$COMPOSE_DIR/compose.yml"
[ -f "$COMPOSE_FILE" ] || COMPOSE_FILE="$COMPOSE_DIR/docker-compose.yml"
log "Found: $COMPOSE_FILE"

compose_services() {
  (cd "$COMPOSE_DIR" && docker compose config --services 2>/dev/null)
}

detect_compose_service() {
  local preferred="$1"
  shift
  local services svc candidate
  services="$(compose_services || true)"

  if [ -n "$preferred" ] && { [ -z "$services" ] || echo "$services" | grep -Fxq "$preferred"; }; then
    echo "$preferred"; return
  fi

  for candidate in "$@"; do
    if echo "$services" | grep -Fxq "$candidate"; then
      echo "$candidate"; return
    fi
  done

  for candidate in "$@"; do
    svc="$(echo "$services" | grep -E "$candidate" | head -1 || true)"
    if [ -n "$svc" ]; then
      echo "$svc"; return
    fi
  done

  echo ""
}

NGINX_SERVICE="$(detect_compose_service "${DOCKER_NGINX_SERVICE:-}" nginx proxy reverse-proxy front)"
MYSQL_SERVICE="$(detect_compose_service "${DOCKER_MYSQL_SERVICE:-}" mysql db mariadb)"
if [ -z "$NGINX_SERVICE" ]; then
  log "ERROR: nginx service not found. Set DOCKER_NGINX_SERVICE=<service>."
  exit 1
fi
if [ -z "$MYSQL_SERVICE" ]; then
  log "ERROR: MySQL service not found. Set DOCKER_MYSQL_SERVICE=<service>."
  exit 1
fi
log "Services: nginx=$NGINX_SERVICE mysql=$MYSQL_SERVICE"

# ---- 1. ログディレクトリをホストに作成 ----
LOG_DIR="$COMPOSE_DIR/logs"
mkdir -p "$LOG_DIR/nginx" "$LOG_DIR/mysql"
log "Created: $LOG_DIR/{nginx,mysql}"

# ---- 2. 専用 override でログ volume マウントを追加 ----
LOG_OVERRIDE_FILE="$COMPOSE_DIR/docker-compose.isucon-logs.yml"
if [ -f "$LOG_OVERRIDE_FILE" ] && ! grep -q 'Generated by setup-docker.sh' "$LOG_OVERRIDE_FILE"; then
  log "ERROR: $LOG_OVERRIDE_FILE exists and was not generated by setup-docker.sh."
  log "  Move it aside or set up log volumes manually to avoid overwriting local changes."
  exit 1
fi
cat > "$LOG_OVERRIDE_FILE" <<EOF
# Generated by setup-docker.sh — exposes container logs to host for analyze.sh
services:
  $NGINX_SERVICE:
    volumes:
      - ./logs/nginx:/var/log/nginx
  $MYSQL_SERVICE:
    volumes:
      - ./logs/mysql:/var/log/mysql
EOF
log "Created: $LOG_OVERRIDE_FILE"

compose_cmd() {
  local compose_args=(-f "$COMPOSE_FILE")
  if [ -f "$COMPOSE_DIR/docker-compose.override.yml" ]; then
    compose_args+=(-f "$COMPOSE_DIR/docker-compose.override.yml")
  fi
  compose_args+=(-f "$LOG_OVERRIDE_FILE")
  (cd "$COMPOSE_DIR" && docker compose "${compose_args[@]}" "$@")
}

# ---- 3. nginx LTSV 設定をホスト側のマウントパスに配置 ----
NGINX_CONF_HOST_DIR="${NGINX_CONF_HOST_DIR:-$COMPOSE_DIR/etc/nginx/conf.d}"
if [ -d "$NGINX_CONF_HOST_DIR" ]; then
  if ! grep -ql 'ltsv' "$NGINX_CONF_HOST_DIR"/*.conf 2>/dev/null; then
    cp "$SCRIPT_DIR/../templates/nginx-ltsv.conf" "$NGINX_CONF_HOST_DIR/ltsv.conf"
    log "Applied nginx LTSV config: $NGINX_CONF_HOST_DIR/ltsv.conf"
  else
    log "nginx LTSV config already applied"
  fi
  if grep -rE '^\s*access_log\s+[^;]+;' "$NGINX_CONF_HOST_DIR" 2>/dev/null | grep -vq 'ltsv'; then
    log "ERROR: some nginx access_log directives do not use ltsv."
    log "  Update them before analyzing logs."
    exit 1
  fi
else
  log "ERROR: $NGINX_CONF_HOST_DIR not found."
  log "  Set NGINX_CONF_HOST_DIR= to the host-mounted nginx conf.d directory."
  log "  If nginx config is not mounted on the host, add LTSV logging inside the nginx container manually."
  exit 1
fi

# ---- 4. コンテナを再起動してオーバーライドを適用 ----
compose_cmd up -d
log "Containers restarted with log volume mounts"

# ---- 5. MySQL が起動するまで待つ ----
# slow query log の有効化には管理権限が必要なため、アプリ接続用 DB_USER/DB_PASS とは分ける。
DB_ADMIN_USER="${DB_ADMIN_USER:-root}"
if [ -z "${DB_ADMIN_PASS:-}" ]; then
  DB_ADMIN_PASS="$(compose_cmd exec -T "$MYSQL_SERVICE" printenv MYSQL_ROOT_PASSWORD 2>/dev/null || true)"
fi
if [ -z "$DB_ADMIN_PASS" ]; then
  log "ERROR: DB_ADMIN_PASS is not set and MYSQL_ROOT_PASSWORD was not found in the MySQL container."
  log "  Set DB_ADMIN_USER and DB_ADMIN_PASS in scripts/env.sh or environment."
  exit 1
fi
log "Waiting for MySQL..."
MYSQL_READY=0
for i in $(seq 1 15); do
  if compose_cmd exec -T "$MYSQL_SERVICE" mysql -u"$DB_ADMIN_USER" -p"$DB_ADMIN_PASS" -e "SELECT 1" &>/dev/null 2>&1; then
    MYSQL_READY=1
    break
  fi
  sleep 2
done
if [ "$MYSQL_READY" != "1" ]; then
  log "ERROR: could not connect to MySQL as $DB_ADMIN_USER."
  log "  Set DB_ADMIN_USER and DB_ADMIN_PASS in scripts/env.sh or environment."
  exit 1
fi

# ---- 6. MySQL スロークエリログを有効化 ----
log "Enabling MySQL slow query log..."
compose_cmd exec -T "$MYSQL_SERVICE" chown mysql:mysql /var/log/mysql 2>/dev/null || true
if compose_cmd exec -T "$MYSQL_SERVICE" mysql -u"$DB_ADMIN_USER" -p"$DB_ADMIN_PASS" -e "
      SET GLOBAL slow_query_log = 1;
      SET GLOBAL slow_query_log_file = '/var/log/mysql/slow.log';
      SET GLOBAL long_query_time = 0;
    " 2>/dev/null; then
  log "MySQL slow query log enabled → $LOG_DIR/mysql/slow.log"
else
  log "ERROR: Failed to enable MySQL slow query log. Check DB_ADMIN_USER/DB_ADMIN_PASS or container health."
  exit 1
fi

# ---- 7. nginx をリロード ----
if compose_cmd exec -T "$NGINX_SERVICE" nginx -s reload 2>/dev/null; then
  log "nginx reloaded with LTSV log format"
else
  log "WARNING: nginx reload failed. Check nginx config syntax."
fi

log ""
log "Setup complete."
log "  For future docker compose commands, include: -f $COMPOSE_FILE -f $LOG_OVERRIDE_FILE"
if [ -f "$COMPOSE_DIR/docker-compose.override.yml" ]; then
  log "  Existing override also needs to be included: -f $COMPOSE_DIR/docker-compose.override.yml"
fi
log "  Run benchmark → bash scripts/analyze.sh"
