#!/bin/bash
# Docker Compose 環境向け ISUCON セットアップ
# - ログをホストに volume マウント（docker-compose.isucon-logs.yml）
# - nginx LTSV ログ設定を適用
# - MySQL スロークエリログを有効化
# 事前に /isucon-survey で scripts/env.sh を生成しておくこと。
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"
source "$SCRIPT_DIR/lib-docker.sh"

# /isucon-survey が生成した env.sh を読む（存在すれば）
load_isucon_env "$SCRIPT_DIR"

log() { echo "[setup-docker] $*"; }

# ---- compose ファイル・サービスを特定 ----
COMPOSE_DIR="$(detect_compose_dir || true)"
if [ -z "$COMPOSE_DIR" ]; then
  log "ERROR: compose.yml not found."
  log "  Run /isucon-survey to generate scripts/env.sh, or set DOCKER_COMPOSE_DIR=<path>."
  exit 1
fi
COMPOSE_FILE="$(detect_compose_file "$COMPOSE_DIR" || true)"
if [ -z "$COMPOSE_FILE" ]; then
  log "ERROR: compose file not found under $COMPOSE_DIR."
  log "  Set DOCKER_COMPOSE_FILE=<absolute path> or DOCKER_COMPOSE_DIR=<path> in scripts/env.sh."
  exit 1
fi
log "Found: $COMPOSE_FILE"

COMPOSE_SERVICES="$(compose_services_for_file "$COMPOSE_DIR" "$COMPOSE_FILE" || true)"
NGINX_SERVICE="$(detect_named_service "$COMPOSE_SERVICES" "${DOCKER_NGINX_SERVICE:-}" nginx proxy reverse-proxy front || true)"
MYSQL_SERVICE="$(detect_named_service "$COMPOSE_SERVICES" "${DOCKER_MYSQL_SERVICE:-}" mysql db mariadb || true)"
if [ -z "$NGINX_SERVICE" ]; then
  log "ERROR: nginx service not found. Set DOCKER_NGINX_SERVICE=<service>."
  exit 1
fi
if [ -z "$MYSQL_SERVICE" ]; then
  log "ERROR: MySQL service not found. Set DOCKER_MYSQL_SERVICE=<service>."
  exit 1
fi
log "Services: nginx=$NGINX_SERVICE mysql=$MYSQL_SERVICE"

# APP_SERVICES が env.sh にあっても、nginx/mysql/cache を除外して override の
# サービスキー重複を防ぐ。
APP_SERVICES="$(filter_compose_app_services "$COMPOSE_SERVICES" "$NGINX_SERVICE" "$MYSQL_SERVICE" "${APP_SERVICES:-}" | tr '\n' ' ' | xargs)"
log "App services: ${APP_SERVICES:-(none detected)}"

# ---- 1. ログディレクトリをホストに作成 ----
LOG_DIR="$COMPOSE_DIR/logs"
mkdir -p "$LOG_DIR/nginx" "$LOG_DIR/mysql"
# MySQL ログは事前に作成して権限を開放する（コンテナ起動後は mysql ユーザー所有になるため）
touch "$LOG_DIR/mysql/slow.log"
chmod 666 "$LOG_DIR/mysql/slow.log"
truncate -s 0 "$LOG_DIR/mysql/slow.log"
log "Created: $LOG_DIR/{nginx,mysql}"

# ---- 1b. MySQL slow query log 設定ファイルを作成 ----
# my.cnf に書くことでコンテナ再起動後も設定が維持される（SET GLOBAL は揮発性のため）
MYSQL_CNF_DIR="$COMPOSE_DIR/etc/mysql"
MYSQL_CNF_FILE="$MYSQL_CNF_DIR/slow-query.cnf"
mkdir -p "$MYSQL_CNF_DIR"
cp "$SCRIPT_DIR/../templates/mysql-slow.cnf" "$MYSQL_CNF_FILE"
log "Created: $MYSQL_CNF_FILE"

# ---- 2. 専用 override でログ volume マウントを追加 ----
LOG_OVERRIDE_FILE="$COMPOSE_DIR/docker-compose.isucon-logs.yml"
if [ -f "$LOG_OVERRIDE_FILE" ] && ! grep -q 'Generated by setup-docker.sh' "$LOG_OVERRIDE_FILE"; then
  log "ERROR: $LOG_OVERRIDE_FILE exists and was not generated by setup-docker.sh."
  log "  Move it aside or set up log volumes manually to avoid overwriting local changes."
  exit 1
fi
{
  echo "# Generated by setup-docker.sh — exposes container logs to host for analyze.sh"
  echo "services:"
  echo "  $NGINX_SERVICE:"
  echo "    volumes:"
  echo "      - ./logs/nginx:/var/log/nginx"
  echo "  $MYSQL_SERVICE:"
  echo "    volumes:"
  echo "      - ./logs/mysql:/var/log/mysql"
  echo "      - ./etc/mysql/slow-query.cnf:/etc/mysql/conf.d/slow-query.cnf:ro"
  if [ "${ISUCON_APP_LANG:-}" = "go" ] && [ -n "$APP_SERVICES" ]; then
    for svc in $APP_SERVICES; do
      echo "  $svc:"
      echo "    environment:"
      echo "      GODEBUG: gctrace=1  # analyze.sh / isucon-analyze が GC ログを解析する"
    done
  fi
} > "$LOG_OVERRIDE_FILE"
log "Created: $LOG_OVERRIDE_FILE"

compose_cmd() {
  local -a compose_args
  if [ -n "${DOCKER_COMPOSE_FILE_ARGS:-}" ]; then
    eval "compose_args=($DOCKER_COMPOSE_FILE_ARGS)"
  else
    compose_args=(-f "$COMPOSE_FILE")
  fi
  if [ -f "$COMPOSE_DIR/docker-compose.override.yml" ] &&
     ! printf '%s\n' "${compose_args[@]}" | grep -Fxq "$COMPOSE_DIR/docker-compose.override.yml"; then
    compose_args+=(-f "$COMPOSE_DIR/docker-compose.override.yml")
  fi
  if ! printf '%s\n' "${compose_args[@]}" | grep -Fxq "$LOG_OVERRIDE_FILE"; then
    compose_args+=(-f "$LOG_OVERRIDE_FILE")
  fi
  (cd "$COMPOSE_DIR" && docker compose "${compose_args[@]}" "$@")
}

compose_file_args_for_log() {
  local -a compose_args
  if [ -n "${DOCKER_COMPOSE_FILE_ARGS:-}" ]; then
    eval "compose_args=($DOCKER_COMPOSE_FILE_ARGS)"
  else
    compose_args=(-f "$COMPOSE_FILE")
  fi
  if [ -f "$COMPOSE_DIR/docker-compose.override.yml" ] &&
     ! printf '%s\n' "${compose_args[@]}" | grep -Fxq "$COMPOSE_DIR/docker-compose.override.yml"; then
    compose_args+=(-f "$COMPOSE_DIR/docker-compose.override.yml")
  fi
  if ! printf '%s\n' "${compose_args[@]}" | grep -Fxq "$LOG_OVERRIDE_FILE"; then
    compose_args+=(-f "$LOG_OVERRIDE_FILE")
  fi
  printf '%q ' "${compose_args[@]}"
}

# ---- 3. nginx LTSV 設定をホスト側のマウントパスに配置 ----
NGINX_CONF_HOST_DIR="${NGINX_CONF_HOST_DIR:-$COMPOSE_DIR/etc/nginx/conf.d}"
if [ -d "$NGINX_CONF_HOST_DIR" ]; then
  # log_format ltsv の定義を配置する
  if ! grep -ql 'log_format ltsv' "$NGINX_CONF_HOST_DIR"/*.conf 2>/dev/null; then
    cp "$SCRIPT_DIR/../templates/nginx-00-ltsv.conf" "$NGINX_CONF_HOST_DIR/00-ltsv.conf"
    log "Applied nginx LTSV log_format: $NGINX_CONF_HOST_DIR/00-ltsv.conf"
  else
    log "nginx LTSV log_format already defined"
  fi
  # access_log を各 server ブロックに注入する（http ブロックのデフォルト combined と混在しないよう server ブロックで上書き）
  for conf in "$NGINX_CONF_HOST_DIR"/*.conf; do
    [ -f "$conf" ] || continue
    if grep -q 'listen ' "$conf" && ! grep -q 'access_log.*ltsv' "$conf"; then
      sed -i 's/\(listen [^;]*;\)/\1\n  access_log \/var\/log\/nginx\/access.log ltsv;/' "$conf"
      log "Injected LTSV access_log into: $conf"
    fi
  done
else
  log "ERROR: $NGINX_CONF_HOST_DIR not found."
  log "  Set NGINX_CONF_HOST_DIR= to the host-mounted nginx conf.d directory."
  log "  If nginx config is not mounted on the host, add LTSV logging inside the nginx container manually."
  exit 1
fi

# ---- 4. コンテナを再起動してオーバーライドを適用 ----
compose_cmd up -d
log "Containers restarted with log volume mounts"

# ---- 5. MySQL が起動するまで待つ ----
# slow query log の有効化には管理権限が必要なため、アプリ接続用 DB_USER/DB_PASS とは分ける。
DB_ADMIN_USER="${DB_ADMIN_USER:-root}"
if [ -z "${DB_ADMIN_PASS:-}" ]; then
  DB_ADMIN_PASS="$(compose_cmd exec -T "$MYSQL_SERVICE" printenv MYSQL_ROOT_PASSWORD 2>/dev/null || true)"
fi
if [ -z "$DB_ADMIN_PASS" ]; then
  log "ERROR: DB_ADMIN_PASS is not set and MYSQL_ROOT_PASSWORD was not found in the MySQL container."
  log "  Set DB_ADMIN_USER and DB_ADMIN_PASS in scripts/env.sh or environment."
  exit 1
fi
log "Waiting for MySQL..."
MYSQL_READY=0
for i in $(seq 1 15); do
  if compose_cmd exec -T "$MYSQL_SERVICE" mysql -u"$DB_ADMIN_USER" -p"$DB_ADMIN_PASS" -e "SELECT 1" &>/dev/null 2>&1; then
    MYSQL_READY=1
    break
  fi
  sleep 2
done
if [ "$MYSQL_READY" != "1" ]; then
  log "ERROR: could not connect to MySQL as $DB_ADMIN_USER."
  log "  Set DB_ADMIN_USER and DB_ADMIN_PASS in scripts/env.sh or environment."
  exit 1
fi

# ---- 6. MySQL スロークエリログを有効化 ----
log "Enabling MySQL slow query log..."
compose_cmd exec -T "$MYSQL_SERVICE" chown mysql:mysql /var/log/mysql 2>/dev/null || true
# my.cnf で設定済みだが SET GLOBAL で即時反映する
if compose_cmd exec -T "$MYSQL_SERVICE" mysql -u"$DB_ADMIN_USER" -p"$DB_ADMIN_PASS" -e "
      SET GLOBAL slow_query_log = 1;
      SET GLOBAL long_query_time = 0;
    " 2>/dev/null; then
  log "MySQL slow query log enabled → $LOG_DIR/mysql/slow.log"
else
  log "ERROR: Failed to enable MySQL slow query log. Check DB_ADMIN_USER/DB_ADMIN_PASS or container health."
  exit 1
fi

# ---- 7. nginx をリロード ----
if compose_cmd exec -T "$NGINX_SERVICE" nginx -s reload 2>/dev/null; then
  log "nginx reloaded with LTSV log format"
  # access.log をホストユーザーが読み書きできるよう権限を開放してリセットする
  compose_cmd exec -T "$NGINX_SERVICE" sh -c 'chmod 666 /var/log/nginx/access.log && truncate -s 0 /var/log/nginx/access.log' 2>/dev/null || true
else
  log "WARNING: nginx reload failed. Check nginx config syntax."
fi

log ""
log "Setup complete."
log "  For future docker compose commands, include: $(compose_file_args_for_log)"
if [ "${ISUCON_APP_LANG:-}" = "go" ] && [ -n "$APP_SERVICES" ]; then
  log "  GODEBUG=gctrace=1 set on: $APP_SERVICES (for bench-locked.sh GC trace capture)"
  ENV_FILE="$SCRIPT_DIR/env.sh"
  if [ -f "$ENV_FILE" ] && ! grep -q '^export APP_SERVICES=' "$ENV_FILE"; then
    echo "export APP_SERVICES='$APP_SERVICES'" >> "$ENV_FILE"
    log "  Added to $ENV_FILE: export APP_SERVICES='$APP_SERVICES'"
  elif [ -f "$ENV_FILE" ]; then
    log "  scripts/env.sh already sets APP_SERVICES, leaving it untouched"
  else
    log "  Add to scripts/env.sh: export APP_SERVICES='$APP_SERVICES'"
  fi
fi
log "  Run benchmark → bash scripts/analyze.sh"
