#!/bin/bash
# ISUCON アプリサーバー初期化
# git init / reports ディレクトリ作成 / (systemd+Go の場合) GC トレース drop-in 設定。
# アプリが動いているサーバーで実行する。
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"

# /isucon-survey が生成した env.sh を読む（webapp パスなど）
[ -f "$SCRIPT_DIR/env.sh" ] && source "$SCRIPT_DIR/env.sh"

log() { echo "[setup-app] $*"; }

git_cmd() {
  if [ "${EUID:-$(id -u)}" -eq 0 ]; then
    local git_user="${SUDO_USER:-}"
    if [ -z "$git_user" ] || [ "$git_user" = "root" ]; then
      git_user="$(stat -c '%U' "$WEBAPP_DIR")"
    fi
    if [ -z "$git_user" ] || [ "$git_user" = "root" ]; then
      log "ERROR: refusing to initialize webapp git as root. Run as the webapp owner or set ISUCON_WEBAPP_DIR correctly."
      exit 1
    fi
    sudo -u "$git_user" git -C "$WEBAPP_DIR" "$@"
  else
    git -C "$WEBAPP_DIR" "$@"
  fi
}

setup_git() {
  WEBAPP_DIR="${ISUCON_WEBAPP_DIR:-/home/isucon/webapp}"
  if [ ! -d "$WEBAPP_DIR" ]; then
    log "webapp dir not found at $WEBAPP_DIR, skipping git setup"
    log "  Set ISUCON_WEBAPP_DIR env var to override"
    return 0
  fi

  if [ -d "$WEBAPP_DIR/.git" ]; then
    log "git already initialized at $WEBAPP_DIR"
    return 0
  fi

  log "Initializing git at $WEBAPP_DIR..."
  git_cmd init
  git_cmd add .
  git_cmd -c user.name="isucon" -c user.email="isucon@isucon" \
    commit -m "initial commit (before optimization)"
  log "git initialized"
}

# ---- systemd + Go: GC トレース用 drop-in を注入 ----
# Docker 環境では setup-docker.sh が docker-compose.isucon-logs.yml に直接書き込むのと同じ役割。
# 本体の unit ファイルは直書きせず、systemd の drop-in (<service>.service.d/) で分離する。
setup_gc_trace_systemd() {
  [ "${ISUCON_RUNTIME:-}" = "systemd" ] || return 0
  [ "${ISUCON_APP_LANG:-}" = "go" ] || return 0
  if [ -z "${APP_SERVICES:-}" ]; then
    log "APP_SERVICES not set, skipping GC trace drop-in. Set APP_SERVICES='<systemd unit name>' in scripts/env.sh to enable."
    return 0
  fi

  local svc dropin_dir dropin_file
  for svc in $APP_SERVICES; do
    if ! systemctl cat "$svc" &>/dev/null; then
      log "WARNING: systemd unit '$svc' not found, skipping GC trace drop-in for it"
      continue
    fi
    # APP_SERVICES の誤字・古い値が無関係な unit 名に一致した場合の事故防止。
    # ISUCON_WEBAPP_DIR が設定されていれば unit の中身がそこを参照しているか確認する。
    if [ -n "${ISUCON_WEBAPP_DIR:-}" ] && ! systemctl cat "$svc" 2>/dev/null | grep -qF "$ISUCON_WEBAPP_DIR"; then
      log "WARNING: systemd unit '$svc' does not reference ISUCON_WEBAPP_DIR ($ISUCON_WEBAPP_DIR), skipping GC trace drop-in for it. Check APP_SERVICES in scripts/env.sh."
      continue
    fi
    dropin_dir="/etc/systemd/system/${svc}.service.d"
    dropin_file="$dropin_dir/isucon-gctrace.conf"
    if [ -f "$dropin_file" ]; then
      if ! sudo grep -q 'Generated by setup-app.sh' "$dropin_file"; then
        log "WARNING: $dropin_file exists and was not generated by setup-app.sh, leaving it untouched"
        continue
      fi
      if sudo grep -qx 'Environment=GODEBUG=gctrace=1' "$dropin_file"; then
        log "$dropin_file already up to date, skipping restart"
        continue
      fi
    fi
    log "Writing $dropin_file (GODEBUG=gctrace=1)..."
    sudo mkdir -p "$dropin_dir"
    sudo tee "$dropin_file" > /dev/null <<'EOF'
# Generated by setup-app.sh — GC trace for analyze.sh / isucon-analyze
[Service]
Environment=GODEBUG=gctrace=1
EOF
    sudo systemctl daemon-reload
    sudo systemctl restart "$svc" \
      || log "WARNING: failed to restart $svc after adding drop-in"
  done
}

mkdir -p "$REPO_DIR/reports"
log "reports dir ready: $REPO_DIR/reports"

setup_git
setup_gc_trace_systemd
