#!/bin/bash
# Docker Compose 環境向け ISUCON セットアップ
# - ログをホストに volume マウント（docker-compose.override.yml）
# - nginx LTSV ログ設定を適用
# - MySQL スロークエリログを有効化
# - scripts/env-docker.sh を生成（analyze.sh が自動 source）
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"

log() { echo "[setup-docker] $*"; }

# ---- compose ファイルを特定 ----
find_compose_dir() {
  if [ -n "${DOCKER_COMPOSE_DIR:-}" ]; then
    realpath "$DOCKER_COMPOSE_DIR"; return
  fi
  for dir in "." "${ISUCON_WEBAPP_DIR:-/home/isucon/webapp}"; do
    [ -z "$dir" ] && continue
    if [ -f "$dir/compose.yml" ] || [ -f "$dir/docker-compose.yml" ]; then
      realpath "$dir"; return
    fi
  done
  echo ""
}

COMPOSE_DIR="$(find_compose_dir)"
if [ -z "$COMPOSE_DIR" ]; then
  log "ERROR: compose.yml not found. Set DOCKER_COMPOSE_DIR=<path> and retry."
  exit 1
fi
COMPOSE_FILE="$COMPOSE_DIR/compose.yml"
[ -f "$COMPOSE_FILE" ] || COMPOSE_FILE="$COMPOSE_DIR/docker-compose.yml"
log "Found: $COMPOSE_FILE"

# ---- 1. ログディレクトリをホストに作成 ----
LOG_DIR="$COMPOSE_DIR/logs"
mkdir -p "$LOG_DIR/nginx" "$LOG_DIR/mysql"
log "Created: $LOG_DIR/{nginx,mysql}"

# ---- 2. docker-compose.override.yml でログ volume マウントを追加 ----
OVERRIDE_FILE="$COMPOSE_DIR/docker-compose.override.yml"
if [ ! -f "$OVERRIDE_FILE" ] || ! grep -q 'logs/nginx' "$OVERRIDE_FILE" 2>/dev/null; then
  cat > "$OVERRIDE_FILE" <<'EOF'
# Generated by setup-docker.sh — exposes container logs to host for analyze.sh
services:
  nginx:
    volumes:
      - ./logs/nginx:/var/log/nginx
  mysql:
    volumes:
      - ./logs/mysql:/var/log/mysql
EOF
  log "Created: $OVERRIDE_FILE"
else
  log "Override already has log mounts, skipping"
fi

# ---- 3. nginx LTSV 設定をホスト側のマウントパスに配置 ----
NGINX_CONF_HOST_DIR="${NGINX_CONF_HOST_DIR:-$COMPOSE_DIR/etc/nginx/conf.d}"
if [ -d "$NGINX_CONF_HOST_DIR" ]; then
  if ! grep -ql 'ltsv' "$NGINX_CONF_HOST_DIR"/*.conf 2>/dev/null; then
    cp "$SCRIPT_DIR/../templates/nginx-ltsv.conf" "$NGINX_CONF_HOST_DIR/ltsv.conf"
    log "Applied nginx LTSV config: $NGINX_CONF_HOST_DIR/ltsv.conf"
  else
    log "nginx LTSV config already applied"
  fi
else
  log "WARNING: $NGINX_CONF_HOST_DIR not found. Set NGINX_CONF_HOST_DIR= to specify nginx conf.d."
fi

# ---- 4. コンテナを再起動してオーバーライドを適用 ----
(cd "$COMPOSE_DIR" && docker compose up -d)
log "Containers restarted with log volume mounts"

# ---- 5. MySQL が起動するまで待つ ----
DB_PASS="$(grep -E 'MYSQL_ROOT_PASSWORD' "$COMPOSE_FILE" 2>/dev/null \
  | grep -oE '[^:=]+$' | tr -d ' "' | head -1 || true)"
DB_PASS="${DB_PASS:-root}"
log "Waiting for MySQL..."
for i in $(seq 1 15); do
  if (cd "$COMPOSE_DIR" && \
      docker compose exec mysql mysql -uroot -p"$DB_PASS" -e "SELECT 1" &>/dev/null 2>&1); then
    break
  fi
  sleep 2
done

# ---- 6. MySQL スロークエリログを有効化 ----
log "Enabling MySQL slow query log..."
(cd "$COMPOSE_DIR" && docker compose exec mysql chown mysql:mysql /var/log/mysql 2>/dev/null || true)
if (cd "$COMPOSE_DIR" && \
    docker compose exec mysql mysql -uroot -p"$DB_PASS" -e "
      SET GLOBAL slow_query_log = 1;
      SET GLOBAL slow_query_log_file = '/var/log/mysql/slow.log';
      SET GLOBAL long_query_time = 0;
    " 2>/dev/null); then
  log "MySQL slow query log enabled → $LOG_DIR/mysql/slow.log"
else
  log "WARNING: Failed to enable MySQL slow query log. Check DB_PASS or container health."
fi

# ---- 7. nginx をリロード ----
if (cd "$COMPOSE_DIR" && docker compose exec nginx nginx -s reload 2>/dev/null); then
  log "nginx reloaded with LTSV log format"
else
  log "WARNING: nginx reload failed. Check nginx config syntax."
fi

# ---- 8. analyze.sh 用の環境変数ファイルを生成 ----
ENV_FILE="$SCRIPT_DIR/env-docker.sh"
cat > "$ENV_FILE" <<EOF
# Docker Compose 環境の analyze.sh 用ログパス設定
# setup-docker.sh が自動生成。analyze.sh が自動 source する。
export NGINX_ACCESS_LOG="$LOG_DIR/nginx/access.log"
export MYSQL_SLOW_LOG="$LOG_DIR/mysql/slow.log"
EOF
log "Created: $ENV_FILE (auto-sourced by analyze.sh)"
log ""
log "Setup complete."
log "  Run benchmark → bash scripts/analyze.sh"
