#!/bin/bash
# setup.sh の変更をすべて元に戻す
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=scripts/lib.sh
source "$SCRIPT_DIR/lib.sh"
STATE_DIR="$SCRIPT_DIR/.setup-state"

log() { echo "[unsetup] $*"; }

pkg_remove() {
  case "$(detect_os_family)" in
    debian) sudo apt-get remove -y "$@" ;;
    rhel)
      if command -v dnf &>/dev/null; then
        sudo dnf remove -y "$@"
      else
        sudo yum remove -y "$@"
      fi
      ;;
    *) log "WARNING: unsupported OS; remove manually: $*" ;;
  esac
}

log "=== ISUCON unsetup start ==="

# alp 削除
if [ -f "$STATE_DIR/alp-installed" ] && [ -f /usr/local/bin/alp ]; then
  sudo rm /usr/local/bin/alp
  rm -f "$STATE_DIR/alp-installed"
  log "Removed /usr/local/bin/alp"
else
  log "alp was not installed by setup-tools.sh, skipping"
fi

# percona-toolkit 削除
if [ -f "$STATE_DIR/percona-toolkit-installed" ] && command -v pt-query-digest &>/dev/null; then
  pkg_remove percona-toolkit
  rm -f "$STATE_DIR/percona-toolkit-installed"
  log "Removed percona-toolkit"
else
  log "percona-toolkit was not installed by setup-tools.sh, skipping"
fi

# nginx LTSV 設定削除
if [ -f /etc/nginx/conf.d/ltsv.conf ]; then
  if ! sudo grep -q 'Generated by setup-nginx.sh' /etc/nginx/conf.d/ltsv.conf; then
    log "nginx ltsv.conf was not generated by setup-nginx.sh, skipping removal"
  else
    sudo rm /etc/nginx/conf.d/ltsv.conf
    sudo nginx -t && sudo systemctl reload nginx
    log "Removed nginx ltsv.conf and reloaded"
  fi
else
  log "nginx ltsv.conf not found, skipping"
fi

# MySQL スロークエリ設定削除
MYSQL_CONF_DIR="$(detect_mysql_conf_dir)"
if [ -n "$MYSQL_CONF_DIR" ] && [ -f "$MYSQL_CONF_DIR/slow-query.cnf" ]; then
  if sudo grep -q 'Generated by setup-mysql.sh' "$MYSQL_CONF_DIR/slow-query.cnf"; then
    sudo rm "$MYSQL_CONF_DIR/slow-query.cnf"
    rm -f "$STATE_DIR/mysql-slow-config-installed"
    log "Removed $MYSQL_CONF_DIR/slow-query.cnf"
  else
    log "$MYSQL_CONF_DIR/slow-query.cnf was not generated by setup-mysql.sh, skipping removal"
  fi
else
  log "mysql slow-query.cnf not found, skipping config file removal"
fi

if [ -f "$STATE_DIR/mysql-slow-enabled" ] && mysql_installed; then
  # 動的に無効化（再起動不要）
  sudo mysql -e "SET GLOBAL slow_query_log = 0;" 2>/dev/null \
    || {
      MYSQL_SVC="$(detect_mysql_service)"
      [ -n "$MYSQL_SVC" ] && sudo systemctl restart "$MYSQL_SVC"
    }
  rm -f "$STATE_DIR/mysql-slow-enabled"
  log "Disabled MySQL slow query log"
else
  log "MySQL slow query log was not enabled by setup-mysql.sh, skipping disable"
fi

log "=== ISUCON unsetup done ==="
